[project]
name = "Tooldelta"
version = "0.0.0"
description = "Plugin Loader for NeteaseRentalServer on Panel"
authors = [{ name = "ToolDelta Studio Staff" }]
requires-python = ">=3.10,<3.13"
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "colorama>=0.4.6,<0.5",
    "pyspeedtest==1.2.7",
    "aiohttp>=3.9.3,<4",
    "flask>=3.0.2,<4",
    "websocket-client>=1.7.0,<2",
    "pyyaml==6.0.1",
    "brotli>=1.1.0,<2",
    "websockets>=12.0,<13",
    "tqdm>=4.66.4,<5",
    "anyio>=4.4.0,<5",
    "requests>=2.32.3,<3",
    "numpy>=2.1.0,<3",
    "protobuf>=6.30.1,<7",
    "grpcio>=1.78.1,<2",
    "msgpack>=1.1.0,<2",
    "nbtlib>=2.0.4,<3",
    "rich>=14.1.0,<15",
    "prompt-toolkit>=3.0.52",
]

[project.urls]
Homepage = "https://github.com/ToolDelta-Basic/ToolDelta"
Repository = "https://github.com/ToolDelta-Basic/ToolDelta"

[tool.uv]

[[tool.uv.index]]
name = "mirrors"
url = "http://mirrors.aliyun.com/pypi/simple/"
default = true

[tool.uv.build-backend]
module-root = ""

[build-system]
requires = ["uv_build>=0.11.14,<0.12.0"]
build-backend = "uv_build"


[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
select = [
    "F",     # Pyflakes
    "W",     # pycodestyle warnings
    "E",     # pycodestyle errors
    "UP",    # pyupgrade
    "ASYNC", # flake8-async
    "C4",    # flake8-comprehensions
    "T10",   # flake8-debugger
    "PYI",   # flake8-pyi
    "PT",    # flake8-pytest-style
    "Q",     # flake8-quotes
    "RUF",   # Ruff-specific rules
]
ignore = [
    "E402",   # module-import-not-at-top-of-file
    "E501",   # line-too-long
    "UP037",  # quoted-annotation
    "RUF001", # ambiguous-unicode-character-string
    "RUF002", # ambiguous-unicode-character-docstring
    "RUF003", # ambiguous-unicode-character-comment
]

[tool.pyright]
typeCheckingMode = "basic"
